### ISSUE TITLE
Some ammo lacks appropriate ammo types.

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtendedRWMod/CombatExtended#1013]
More for my own tracking purposes than anything else. Some CE ammo, some FT. The following ammos need the respective ammo types added.
- Crossbow: Flaming, Posion.
- Webley: AP, HP
- FT High Caliber Shells: Some lack FMJ, some lack Sabot.

**Comment by Alicecomma** [comment]
Why should those shells have FMJ?

**Comment by N7Huntsman** [comment]
Sorry, I guess it's a little misleading to call them "high caliber shells," isn't it? There are a few _high caliber ammunition_ types coming from FT that need additional ammo types to match CE's ammo policy of High Caliber calibers getting FMJ, AP-I, AP-HE, and Sabot ammo types.

**Comment by N7Huntsman** [comment]
Resolved by #1036
