### ISSUE TITLE
M74 Incendiary rocket - adjust stackLimit or stack display graphics to depict real-life clip size

### ISSUE THREAD

**Issue by sumghai** [CombatExtendedRWMod/CombatExtended#1037]
### Summary

The M74 Incendiary rockets are used by the M202 FLASH launcher, and the rockets are typically issued in an en bloc clip of four, rather than loaded individually into the launcher. 

Ideally, this should be reflected in the stack display of the ingame M74 ammo item.

### Current State

Currently, the M74 rockets in CE have a `stackLimit` of 25, and using the standard `Graphic_StackCount` graphicClass, we would see:

Stack size | Graphic displayed
--- | --- 
1|![M74_a.png](https://raw.githubusercontent.com/CombatExtendedRWMod/CombatExtended/Development/Textures/Things/Ammo/Rocket/M74/M74_a.png)
2~24|![M74_b.png](https://raw.githubusercontent.com/CombatExtendedRWMod/CombatExtended/Development/Textures/Things/Ammo/Rocket/M74/M74_b.png)
25|![M74_c.png](https://raw.githubusercontent.com/CombatExtendedRWMod/CombatExtended/Development/Textures/Things/Ammo/Rocket/M74/M74_c.png)

Whereas we should ideally have:

Stack size | Graphic displayed
--- | --- 
1|![M74_a.png](https://raw.githubusercontent.com/CombatExtendedRWMod/CombatExtended/Development/Textures/Things/Ammo/Rocket/M74/M74_a.png)
2~3|![M74_b.png](https://raw.githubusercontent.com/CombatExtendedRWMod/CombatExtended/Development/Textures/Things/Ammo/Rocket/M74/M74_b.png)
4|![M74_c.png](https://raw.githubusercontent.com/CombatExtendedRWMod/CombatExtended/Development/Textures/Things/Ammo/Rocket/M74/M74_c.png)

### Proposed Solutions
* **Option 1** - Simply set the `stackLimit` to 4
  * The main disadvantage is that this drastically reduces the amount of M74 rockets that can be stored per cell, and players would need more storage space even for a small stockpile of rockets
* **Options 2** - Set the `stackLimit` to a multiple of 4 (20 or 24), and use the `Graphic_StackCountRanged` graphicClass introduced from the FT merger to precisely control which graphic is displayed at what intermediate stack size (the ammo graphics need to be renamed slightly, since `Graphic_StackCountRanged` reads the number embedded in the filenames for the intermediate stack size)
  * Allows more rockets to be stored per cell, while still visually accurate

### Assignment

I (@sumghai) can do this easily, if given the go-ahead.

**Comment by Alicecomma** [comment]
If accuracy of displayed ammo graphics is important, one could draw more images by hand or write C# code to automatically generate stack size images up to N pieces of ammo.

**Comment by sumghai** [comment]
> If accuracy of displayed ammo graphics is important, one could draw more images by hand or write C# code to automatically generate stack size images up to N pieces of ammo.

As mentioned elsewhere on the FT issue tracker, your proposed methods would involve loading additional (redundant) textures, is imprecise for any arbitrary intermediate ranges, and inelegant.

If we ignore FT's (crude) implementation of power cell ammo types, a good example of `StackCountRanged` usage can be found in the [12mm Railgun caliber defs](https://github.com/CombatExtendedRWMod/CombatExtended/blob/Development/Defs/Ammo/Advanced/12mmRailgun.xml) and [graphics](https://github.com/CombatExtendedRWMod/CombatExtended/tree/Development/Textures/Things/Ammo/Railgun/HighCaliber).

I will make a PR shortly for the M74 rockets, with the `stackLimit` set to 24 to minimize disruption in existing saves.

**Comment by Alicecomma** [comment]
Okay but why is it so important that specifically those ammo types have such specific stackCount graphics up to the first 30 bullets

**Comment by sumghai** [comment]
Visual preference.

Railgun rounds were not intended to be shown individually (like conventional cartridges), but in en bloc clips instead.

**Comment by Alicecomma** [comment]
Makes sense, it does look better this way. The current jumps in ammo graphics are somewhat jarring.

What would constitute a power-cell style ammo framework?

**Comment by sumghai** [comment]
> What would constitute a power-cell style ammo framework?

I will open a separate issue later today (to avoid digressing this topic further), but the "power cell" framework would basically allow a single ammo item to contain multiple shots, like a battery or fuel tank.
