### ISSUE TITLE
CE Royalty [Balance phase]

### ISSUE THREAD

**Issue by Alicecomma** [CombatExtendedRWMod/CombatExtended#1064]
-Finished-

**Comment by Alicecomma** [comment]
Todo
----

Test abilities:
- Painblock
- Stun
- Burden
- BlindingPulse
- EntropyLink
- Beckon
- VertigoPulse
- ChaosSkip
- Skip
- Wallraise
- Smokepop
- Focus
- Berserk
- Invisibility
- BerserkPulse
- ManhunterPulse
- MassChaosSkip

Patch FactionDef Empire

Patch added body parts:
- Coagulator - this reduces blood loss, see if it should be balanced to fit stabilization, new bleed rates etc
- ToughskinGland - armour values added by this hediff should be changed to be balanced with CE
- ArmorskinGland - armour values added by this hediff should be changed to be balanced with CE
- StoneskinGland - armour values added by this hediff should be changed to be balanced with CE
- (optional) NuclearStomach - should honestly explode on death
- DrillArm - added verb should be balanced with CE
- FieldHand - added verb should be balanced with CE
- HandTalon - added verb should be balanced with CE
- ElbowBlade - added verb should be balanced with CE
- KneeSpike - added verb should be balanced with CE
- VenomFangs - added verb should be balanced with CE
- VenomTalon - added verb should be balanced with CE
- PsychicInvisibility // HediffComp_Invisibility - the effects of this should change hit chances or something in CE

**Comment by N7Huntsman** [comment]
What did you have in mind for PowerClaw, JoyWire, and Painstopper that might need patched?

**Comment by Alicecomma** [comment]
Royalty patches them to be craftable and to require new research. If that's balanced enough or whatever then I'd think they're fine as-is

**Comment by Alicecomma** [comment]
Finished (XML)
----

<details><summary>Test abilities</summary>

- [x] Ability: Painblock
- [x] Ability: Burden
- [x] Ability: EntropyLink
- [x] Ability: Beckon
- [x] Ability: ChaosSkip
- [x] Ability: Skip
- [x] Ability: Smokepop
- [x] Ability: Focus
- [x] Ability: Invisibility
- [x] Stun
- [x] BlindingPulse
- [x] VertigoPulse
- [x] Wallraise
- [x] Berserk
- [x] BerserkPulse
- [x] ManhunterPulse
- [x] MassChaosSkip

</details>

- [x] Buildings: UnstablePowerCell - should use ExplosionCE, perhaps add some nice fragments too
- [x] Buildings: Defoliator - should use ExplosionCE, perhaps add some nice fragments too
- [x] Buildings: MechCapsule - rebalance CompProperties_PawnSpawnOnWakeup's points value to CE's combat power for the respective pawns
- [x] Buildings: MechAssembler - same thing, except balance it so it's not impossible to beat
- [x] Buildings: MechDropBeacon - rebalance CompProperties_PawnSpawnOnWakeup's points value to CE's combat power for the respective pawns
- [x] Patch FactionDef Empire

<details><summary>Patch added body parts</summary>

- [x] ToughskinGland - armour values added by this hediff should be changed to be balanced with CE
- [x] ArmorskinGland - armour values added by this hediff should be changed to be balanced with 
CE
- [x] StoneskinGland - armour values added by this hediff should be changed to be balanced with CE
- [x] DrillArm - added verb should be balanced with CE
- [x] FieldHand - added verb should be balanced with CE
- [x] HandTalon - added verb should be balanced with CE
- [x] ElbowBlade - added verb should be balanced with CE
- [x] KneeSpike - added verb should be balanced with CE
- [x] VenomFangs - added verb should be balanced with CE
- [x] VenomTalon - added verb should be balanced with CE
- [x] Bodyparts: PsychicInvisibility // HediffComp_Invisibility - the effects of this should change hit chances or something in CE

</details>

<details><summary>Patch buildings</summary>

- [x] ShieldGeneratorMortar, ShieldGeneratorBullets - check if EMP can disable it, fix CompProperties_ProjectileInterceptor if it doesn't work (quite likely RimWorld.CompProjectileInterceptor.CheckIntercept(Projectile projectile, Vector3 lastExactPos, Vector3 newExactPos) needs to be changed to allow ProjectileCE as well)
- [x] Turret_AutoMiniTurret
- [x] Gun_MiniTurretMech - patch as CE weapon
- [x] Bullet_MiniSlug - patch as CE bullet or something
- [x] Turret_AutoChargeBlaster
- [x] Gun_ChargeBlasterHeavyTurret
- [x] Turret_AutoInferno
- [x] Gun_InfernoCannonTurret
- [x] Turret_AutoMortar
- [x] Artillery_AutoMortar

</details>

<details><summary>Patch pawnKinds</summary>

- [x] Empire_Common_Trader
- [x] Empire_Fighter_Janissary
- [x] Empire_Fighter_Champion
- [x] Empire_Fighter_Cataphract
- [x] Empire_Fighter_StellicGuardRanged
- [x] Empire_Fighter_StellicGuardMelee
- [x] Empire_Royal_NobleWimp
- [x] Empire_Royal_Yeoman
- [x] Empire_Royal_Esquire
- [x] Empire_Royal_Knight
- [x] Empire_Royal_Praetor
- [x] Empire_Royal_Baron
- [x] Empire_Royal_Count
- [x] Empire_Royal_Duke
- [x] Empire_Royal_Consul
- [x] Empire_Royal_Stellarch

</details>

<details><summary>Patch weapons</summary>

- [x] MeleeWeapon_MonoSwordBladelink
- [x] MeleeWeapon_ZeusHammerBladelink
- [x] MeleeWeapon_PlasmaSwordBladelink
- [x] MeleeWeapon_Axe
- [x] MeleeWeapon_Warhammer
- [x] MeleeWeapon_MonoSword
- [x] MeleeWeapon_Zeushammer
- [x] MeleeWeapon_PlasmaSword
- [x] MeleeWeapon_PsyfocusStaff

</details>

<details><summary>Patch apparel</summary>
 
- [x] Apparel_PsyfocusHelmet
- [x] Apparel_PsyfocusShirt
- [x] Apparel_PsyfocusVest
- [x] Apparel_PsyfocusRobe
- [x] Apparel_ShirtRuffle
- [x] Apparel_Corset
- [x] Apparel_VestRoyal
- [x] Apparel_RobeRoyal
- [x] Apparel_HatLadies
- [x] Apparel_HatTop
- [x] Apparel_Coronet
- [x] Apparel_Crown
- [x] Apparel_ArmorCataphract
- [x] Apparel_ArmorHelmetCataphract

</details>

<details><summary>Patch traders</summary>

- [x] Base_Empire_Standard - add ammo and whatever else CE adds to traders
- [x] Empire_Caravan_TraderGeneral
- [x] Orbital_Empire

</details>

C# tests
----

- [x] Test whether CE projectiles (mortar and normal projectiles separately) are intercepted by the mech shields
- [x] Test whether Mech ammo beacons are spawned with every mech raid
- [x] Test whether they drop ammo for mech turrets
- [x] Test whether they work for player turrets

Changes in Royalty
----

<details><summary>Open</summary>

Defs/
- AbilityDefs/, Psycast ability class, AbilityDefs: Painblock, Stun, Burden, BlindingPulse, EntropyLink, Beckon, VertigoPulse, ChaosSkip, Skip, Wallraise, Smokepop, Focus, Berserk, Invisibility, BerserkPulse, ManhunterPulse, MassChaosSkip. Each with own verbs and such.
- FactionDefs/, FactionDef: Empire, should be compared to CE faction treatment
- HediffDefs/, MANY new bodyparts to be patched.. among others?
- MentalStateDefs/, MentalBreakDef: WildDecree; perhaps important
- PawnKinds/, PawnKindDef: Many new pawnkinddefs to be patched
- Sites/Parts/, Perhaps should be balanced somehow
- ThingDefs_Buildings/, New turrets and mech buildings to be balanced and patched
- ThingDefs_Misc/, New apparel to be patched, new weapons (Melee Bladelink, Medieval, Ultratech; Orbital weapons; Psychic weapons)
- TraderKindDefs/, Should be patched to allow ammo, and perhaps other things - compare to current patches

Patches/
- Recipes_Prosthetics: Adds research to PowerClaw, JoyWire and Painstopper

<details><summary>Seemingly irrelevant changes</summary>

Effects/, IncidentDefs/, QuestScriptDefs/, ResearchProjectDefs/, TerrainDefs/

</details>

<details><summary>Irrelevant changes</summary>

Defs/
- DutyDefs/, GatheringDefs/, HairDefs/, JobDefs/, Joy/, Needs/, Rooms/, RoyalTitles/, SketchResolverDefs/, SongDefs/, SoundDefs/, TaleDefs/, ThoughtDefs/, TipSetDefs/, Tutor/

Patches/
- HighCulture_Joy

</details>

</details>
