### ISSUE TITLE
translate strings

### ISSUE THREAD

**Issue by dodther** [CombatExtendedRWMod/CombatExtended#1106]
This string not contaunt in xml files and i cant translate this.
![2020-03-19_21-57-57 (2)](https://user-images.githubusercontent.com/15664548/77067566-dc95ca00-6a30-11ea-8550-cb7105ccb612.png)

**Comment by dodther** [comment]
![2020-03-19_23-41-44](https://user-images.githubusercontent.com/15664548/77073853-a14cc880-6a3b-11ea-9443-a70fda8214ad.png)
![2020-03-19_23-45-14](https://user-images.githubusercontent.com/15664548/77073906-b6c1f280-6a3b-11ea-933f-f7d41af2dd50.png)

**Comment by Alicecomma** [comment]
These are vanilla strings:

"DamageLower", "Tool", "SecondsPerAttackLower" etc.

**Comment by dodther** [comment]
but mmRHA, MPa, "weapon penetration factor" and more no in vanilla.
https://github.com/CombatExtendedRWMod/CombatExtended/search?q=%22weapon+penetration+factor%22&unscoped_q=%22weapon+penetration+factor%22

![2020-03-22_09-09-08 (2)](https://user-images.githubusercontent.com/15664548/77238590-55597980-6c1d-11ea-9ad5-4be72b2c339e.png)
![2020-03-22_09-12-03 (2)](https://user-images.githubusercontent.com/15664548/77238592-58546a00-6c1d-11ea-8053-c4bc2d29ab2d.png)

**Comment by Alicecomma** [comment]
What would you like to change them into, since Pa and m are SI units. Is there a different name for RHA in different languages? Could add them as keyed strings.

**Comment by Alicecomma** [comment]
Alright added in referenced commit.

New in Keys.xml:
```
  <CE_cells>c</CE_cells>
  <CE_degrees>°</CE_degrees>
  <CE_meters>m</CE_meters>
  <CE_WeaponPenetrationFactor>Weapon penetration factor</CE_WeaponPenetrationFactor>
  <CE_AdjustedForWeapon>Adjusted for weapon</CE_AdjustedForWeapon>
  <CE_DPS>Damage per second</CE_DPS>
  <CE_DamageVariation>Damage variation</CE_DamageVariation>
  <CE_FinalAverageDamage>Final average damage</CE_FinalAverageDamage>
  <CE_WielderSkillLevel>Wielder skill level</CE_WielderSkillLevel>
```

New in Descriptions.xml:
```
    <CE_DescBaseDamage>Base damage</CE_DescBaseDamage>
    <CE_DescSharpPenetration>Sharp penetration</CE_DescSharpPenetration>
    <CE_DescBluntPenetration>Blunt penetration</CE_DescBluntPenetration>
```
