### ISSUE TITLE
Not serious, Not a bug - Colonists throw infinite horseshoes with high accuracy

### ISSUE THREAD

**Issue by SheepWulf** [CombatExtendedRWMod/CombatExtended#1144]
### Basic Information

**Operating System**: Windows 10 64-bit **Physical Memory/RAM Capacity**: 32 GB

**RimWorld Version**: Release 1.1 - 1.1.2554  
**CE Version:** None, 1.1 Steam version not yet publicly released; still in public testing 

**Affected Mod(s) and Version(s):**
* Core

**Summary of Issue:** Colonist magically throw an infinite number of horseshoes that they summon out of thin air. They also manage to hit the horseshoe pin with surprisingly high accuracy compared to hitting with a weapon without CE.

### Detailed Information

**What is the expected/correct behavior?:** 
* Horseshoes should be crafted from steel/metal. 
* Colonists would then load the crafted horseshoes into their inventory. 
* They can then use the horseshoes on the horseshoe pin or on their enemies with accuracy according to their skill, then pick up the thrown horseshoes after.

**What is the actual behavior?:** 
* Skill type is known as "Shooting" instead of "Aiming", "Weapon Accuracy/Handling", or having a separate skill for throwing. 
* Colonists cannot utilize their superior horseshoe throwing abilities and infinite supply to annihilate their enemies.
* Colonists have horseshoes despite not necessarily having horses (and horses not being in game until the 1.1 update). There are no alternative shoes for other types of pack animals. 

**Steps to reproduce the problem:**
1. Started a new savegame with Core
2. Built a horseshoe pin
2a. Did not craft horseshoes
3. Colonists proceed to throw horseshoes at horseshoe pin

**Screenshots:**
![Horseshoe_and_Horseshoes_Pin](https://user-images.githubusercontent.com/57203426/77689373-eca13280-6f77-11ea-9b2e-e5d59d581b11.png)

**Error Messages / Log Files:**
None

**Declarations of Due Diligence**
- [ ] (Tick) By submitting this bug report, I declare that:

* I have tested to make sure a new savegame works with only Core and CE
* I have narrowed down the affected mod(s), by testing them individually or through a binary search
* I have searched the issue tracker, and made sure this issue hasn't been reported before
* I am reporting only one issue at a time, and not combining several issues in one report
* I understand that the CE team reserves the right to close my issue at any time, regardless of whether or not my problem has been resolved, if I have been found to not have performed the due diligence required

------------
Thanks to everyone working on CE for all your hard work. I hope this was at least a little funny. Looking forward to the stable release.

**Comment by Alicecomma** [comment]
I like it. Gives you a real dilemma between using horseshoes on horses for increased speed and throwing them at a stick for increased shooting skill.
