### ISSUE TITLE
Elite Crew faction member spawn with no ammo for their guns

### ISSUE THREAD

**Issue by Tittymcswaggy** [CombatExtendedRWMod/CombatExtended#1155]
Elite Crew apparently spawn in with no ammo to use for their guns , their guns are CE patched

**Comment by sumghai** [comment]
I presume you're running one of the developmental builds of CE from the `zhrocks11dev` branch?

If so, could you please tell me which of the following pawn defNames are having this problem?:
* RH_EliteCrew_Scout
* RH_EliteCrew_Grunt
* RH_EliteCrew_CQB
* RH_EliteCrew_CQB_TierII
* RH_EliteCrew_Assault
* RH_EliteCrew_Assault_TierII
* RH_EliteCrew_Marksman
* RH_EliteCrew_Marksman_TierII
* RH_EliteCrew_Gunner
* RH_EliteCrew_Grenadier
* RH_EliteCrew_Boss
* RH_EliteCrew_Elite
* RH_EliteCrew_Trader
* RH_EliteCrew_Sniper
* RH_EliteCrew_Bomber

**Comment by Tittymcswaggy** [comment]
Sorry i forgot to tell you guys , yes it is the current beta of 1.1 CE and all of them have this problem

**Comment by sumghai** [comment]
Bug confirmed - a number of PatchOps incorrectly referenced a particular melee weapon, and once that PatchOp failed it cascaded and caused other PatchOps for adding ammo to pawns to also fail.

A fix has been submitted as PR #1156, and is awaiting approval.

**Comment by Tittymcswaggy** [comment]
Thank you
