### ISSUE TITLE
Stopping something from reloading a turret locks it into a permenant 'reloading' state

### ISSUE THREAD

**Issue by MMMiracles** [CombatExtendedRWMod/CombatExtended#1168]
If a pawn is interrupted by something while reloading a turret (getting suppressed, downed, ect), the turret gets locked in the 'reloading' state and can't be told to reload anymore, switching ammo types and un/reinstalling doesn't work to resolve the issue. 

Pretty easy to reproduce, just tell a pawn to reload a turret and while they're interacting with it just do something that'd cause them to break off from it (i.e damage till down dev tool).

**Comment by Alicecomma** [comment]
Quite likely long-standing bug, since the jobdriver doesn't have any job end conditions for the pawn being downed, dead or damaged.

**Comment by Alicecomma** [comment]
Get latest version and retry, I added several job end conditions.
