### ISSUE TITLE
AndroidTiers item not supported

### ISSUE THREAD

**Issue by No3371** [CombatExtendedRWMod/CombatExtended#1170]
![圖片](https://user-images.githubusercontent.com/1814971/78132141-c9cabe80-744e-11ea-964a-ae44fc0f1394.png)

Just FYI, a weapon (not sure about more or not) is not supported, but the mod is marked in the compatible mod list.

Using zhrocks11's branch.

**Comment by sumghai** [comment]
@No3371 - I cannot reproduce your problem, as the Anti-Mech Rifle works fine in my own setup:

* Harmony 2.0.0.8
* Core (RimWorld 1.1.2589)
* Combat Extended (zhrocks11 branch, last commit 6a2c839 on 1 April 2020 2:01 PM GMT+8)
* Humanoid Alien Races 2.0 (GitHub version, last updated 20 Feb 2020)
* Android Tiers 2.0.2

Please make sure you have updated all your mods to the latest versions, and try reproducing your issue using the same setup I have above.

**Comment by No3371** [comment]
The errors stopped showing up after updated to latest version. thanks.
