### ISSUE TITLE
Gun Charge Blaster Vanilla Mech Weapon no Melee Damage Value Error

### ISSUE THREAD

**Issue by Wolvgar** [CombatExtendedRWMod/CombatExtended#1177]
Red Error on Load 

Trying to get stat MeleeDamageAverage from Gun_ChargeBlasterHeavy which has no support for Combat Extended.

I belive it is a vanilla mech weapon so i do not understand why it is throwing an error. Ofc i could ignore but iam rebuilding a CE compilation and newbs would bugger me WHY you know.

Best regards.

**Comment by N7Huntsman** [comment]
CE certainly patches the HCB with an appropriate melee tool.
```
  <Operation Class="PatchOperationAdd">
    <xpath>Defs/ThingDef[defName="Gun_ChargeBlasterHeavy"]</xpath>
    <value>
      <tools>
        <li Class="CombatExtended.ToolCE">
          <label>barrel</label>
          <capacities>
            <li>Blunt</li>
          </capacities>
          <power>10</power>
          <cooldownTime>1.9</cooldownTime>
          <armorPenetration>0.118</armorPenetration>
          <linkedBodyPartsGroup>Barrel</linkedBodyPartsGroup>
        </li>
      </tools>
    </value>
  </Operation>
```
I'd recommend you go through your mod list and potentially look for another mod that messes with the HCB melee. As a test, you might move CE towards the bottom of your mod list to see if the issue goes away (though I wouldn't suggest this as a solution, as it's liable to create other issues.)

**Comment by Nyamses** [comment]
Hello, I have the same error (Log gets flooded with it), but only when clicking on the "link" to see information on the Heavy Charge Blaster.

I placed all 3 CE mods on the bottom of the list (CE 1.1, CE Ranged, CE Melee) and the error still occurs. I have no other mods that change/add weapons and/or changes Mechs.

On the info panel, the Heavy Charge Blaster has no value for Melee Armor Penetration or Melee Damage, also showing 0.00 DPS.

I'm not sure if it's related, but maybe it's also what's causing Centipedes to just Wander/Stand passively, even when having targets within range of their weapons and remaining passive while being attacked, both in ranged and in melee combat.

On 3 raids with 3-4 Centipedes, only 1 would ever attack my base, the other 2-3 would suffer from the mentioned Wander/Stand passively bug.

**Comment by Wolvgar** [comment]
> 
> 
> Hello, I have the same error (Log gets flooded with it), but only when clicking on the "link" to see information on the Heavy Charge Blaster.
> 
> I placed all 3 CE mods on the bottom of the list (CE 1.1, CE Ranged, CE Melee) and the error still occurs. I have no other mods that change/add weapons and/or changes Mechs.
> 
> On the info panel, the Heavy Charge Blaster has no value for Melee Armor Penetration or Melee Damage, also showing 0.00 DPS.

it was a mod interferance on my side
it was a filter mod more material filters or something not sure if patched.
check your modlist id say o7
