### ISSUE TITLE
Vanilla Weapons Expanded relies on research defs removed by Combat Extended

### ISSUE THREAD

**Issue by MadaraUchiha** [CombatExtendedRWMod/CombatExtended#1199]
VWE\1.1\Defs\ResearchProjectDefs\ResearchProjects_Various.xml:80has the following:

```xml
	<ResearchProjectDef>
		<defName>VWE_HeavyWeapons</defName>
		<label>heavy weapons</label>
		<description>Construct heavy weapons that offer superior firepower, at the cost of being very physically demanding.</description>
		<baseCost>2000</baseCost>
		<techLevel>Industrial</techLevel>
		<prerequisites>
			<li>HeavyTurrets</li>
		</prerequisites>
		<researchViewX>12.00</researchViewX>
		<researchViewY>3.35</researchViewY>
	</ResearchProjectDef>
```

(This also happens for Vanilla Furniture Expanded - Security Module, but that one is not supported by CE and has no patch as of yet, whenever that patch is made, this issue should be referenced)

Combat Extended removes that (as well as SniperTurret, which VFES relies upon), but doesn't patch VWE to provide an alternative. This causes an error at load time 

```
Could not resolve cross-reference to Verse.ResearchProjectDef named HeavyTurrets (wanter=prerequisites)
Verse.Log:Error(String, Boolean)
Verse.DirectXmlCrossRefLoader:TryResolveDef(String, FailMode, Object)
Verse.WantedRefForList`1:TryResolve(FailMode)
Verse.<>c__DisplayClass14_1:<ResolveAllWantedCrossReferences>b__0(WantedRef)
Verse.<>c__DisplayClass6_1`1:<ParallelForEach>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
```

**Comment by Tourman36** [comment]
@onigamii 

Vanilla Furniture Expanded - Security shows as having 1.1 comparability on Steam; is that not accurate? It worked fine under 1.1 without CE.

**Comment by onigamii** [comment]
[This is the patch i made](https://steamcommunity.com/sharedfiles/filedetails/?id=1965337447) and as you can see it's only compatible with 1.1 for now. Don't know where you're seeing this.

**Comment by MadaraUchiha** [comment]
@onigamii I am somewhat confused. Who is "responsible" for hosting the patch? CE or VFE? I've mentioned FVE-S as a "whenever CE ends up supporting this" more than anything else.

Yes, this patch appears to work well from the repo, my apologies, I haven't noticed. Any ETA on when it arrives to Steam? I've switched back to the GitHub version for now, but the update experience is more seamless through there.

Regardless, this issue can be closed, as it is, in principle, already fixed :).
