### ISSUE TITLE
Issue with Mortar

### ISSUE THREAD

**Issue by MikkoGara** [CombatExtendedRWMod/CombatExtended#1204]
Hi.
I have an issue with mortar.
I can't load it with any type of ammo. It not shows the option to load.

**Comment by onigamii** [comment]
Manned turrets are bugged atm and it's being looked at.

**Comment by CyanSam** [comment]
If you have disabled the ammunition system it's expected to happen. You can only load HE shells with the system turned off.

**Comment by MikkoGara** [comment]
So, with system turned  on I can't use mortars?

**Comment by N7Huntsman** [comment]
Duplicated of #1188
