### ISSUE TITLE
[Fix in #1012] Can't change ammo type of multiple select turrets simultaneously

### ISSUE THREAD

**Issue by JonnyNova** [CombatExtendedRWMod/CombatExtended#460]
Small UX issue, the reload gizmo doesn't override `InheritInteractionsFrom` from `Verse.Gizmo` which disallows players setting the ammo type of several emplacements at the same time.

I did some research into the code and it looks like it would require a restructure of the flow since `InheritInteractionsFrom` happens immediately on clicking of the gizmo before the user selects the ammo type from the drop down menu.

**Comment by Alicecomma** [comment]
Relevant code in Gizmos/Command_Reload.cs
- Add public override InheritInteractionsFrom(Gizmo other)
- Copy form of RimWorld.Command_SetTargetFuelLevel.InheritInteractionsFrom(Gizmo other)
- Within remaining methods, use the list of supplied other gizmos

**Comment by Alicecomma** [comment]
Coming soon: reload, unload and change ammo types on any number of selected pawns, turrets or both.

![image](https://user-images.githubusercontent.com/4662406/74878534-d0521a80-5367-11ea-8c95-f5d90d4fb61a.png)

![image](https://user-images.githubusercontent.com/4662406/74878617-f11a7000-5367-11ea-919f-d6b9fab74663.png)

**Comment by Alicecomma** [comment]
The amount of ammousers with a certain ammo category active is displayed, along with how many could have that category active:

![image](https://user-images.githubusercontent.com/4662406/74881153-1c538e00-536d-11ea-86f0-9df951db5233.png)
