### ISSUE TITLE
EMP slug shotgun equipped pawns don't attack non-mechanoids

### ISSUE THREAD

**Issue by Clythoris** [CombatExtendedRWMod/CombatExtended#465]
When an enemy spawns with a shotgun and EMP amunition, they basically become passive and won't attack anything what isn't a mechanoid. Even though EMP slugs do deal damage to pawns.

**Comment by Clythoris** [comment]
[20:13] Alistaire: Prefix that shit
// Verse.VerbUtility
public static bool IsEMP(this Verb verb)
{
    return verb.GetDamageDef() == DamageDefOf.EMP;
}

**Comment by LockdownX7** [comment]
Fixed in #952.
