### ISSUE TITLE
Mechanoids Extraordinaire patch not cross-referencing.

### ISSUE THREAD

**Issue by f0xhunt** [CombatExtendedRWMod/CombatExtended#676]
I get these errors from my log file.

```
Could not resolve cross-reference: No Verse.BodyPartGroupDef named TailBlade found to give to CombatExtended.ToolCE left fist
Verse.Log:Error(String, Boolean)
Verse.WantedRefForObject:TryResolve(FailMode)
Verse.DirectXmlCrossRefLoader:ResolveAllWantedCrossReferences(FailMode)
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```

The same error message applies to UpperLeftMechaTentacle, UpperRightMechaTentacle, LowerLeftMechaTentacle, and LowerRightMechaTentacle.

I am not entirely sure what this error message precisely means but I am guessing CE is missing the right body parts for the mechs. Maybe it's just a typo. I don't know how this translates to actual gameplay, kraken go down when I shoot them.

**Comment by NoImageAvailable** [comment]
1.0 rolled a bunch of side-specific parts into one, e.g. left/right hand -> hand. The patch is probably referencing the wrong format.

**Comment by f0xhunt** [comment]
So for a creature that has multiple "hands," you get this issue.

**Comment by E-Gamma-102** [comment]
I get the same error for the newest version of the mod, I'm sorry but has this been fixed?
