### ISSUE TITLE
Compatibility with mod: Combat Training

### ISSUE THREAD

**Issue by gittywithexcitement** [CombatExtendedRWMod/CombatExtended#708]
Hello, 

CE and [Combat Training](https://github.com/Kriil/rimworld-combat-training/) do not seem to get along (game crashes after a little while, and other things). I was trying to figure out why; I downloaded both source codes, and was reading through. As I'm unfamiliar with either mod, and not familiar with Rimworld modding, I didn't make much headway. Could you provide any pointers to places in CE code or Combat Training that might conflict? Mostly I just want a job that levels up my shooting; I don't care if the Combat Training mod works imperfectly.

Thanks!

**Comment by LockdownX7** [comment]
> Mostly I just want a job that levels up my shooting

If that's the only requirement, Training Console should work fine as an alternative.
