### ISSUE TITLE
Switching Ammo on/off/on causes turrets to lose their gizmo and makes pawns reload them ad infinitum

### ISSUE THREAD

**Issue by Alicecomma** [CombatExtendedRWMod/CombatExtended#760]
- Turret gizmos should reset when the ammo system is reset
- I don't know why pawns reload them forever; reinstalling the turret doesn't fix the problem, the gizmo is just gone. Spawning a new turret is the only way to fix it.

**Comment by NoImageAvailable** [comment]
Switching ammo on/off on an existing colony is an explicitly unsupported operation.

**Comment by Alicecomma** [comment]
Then there should be a warning issued when doing so

**Comment by NoImageAvailable** [comment]
There is

![Untitled](https://user-images.githubusercontent.com/13934439/63687483-15582280-c805-11e9-9430-e537cc6809de.png)

**Comment by Alicecomma** [comment]
I think the following things should happen:

- The warning should only show when toggling the ammo system in a colony
- The warning should come BEFORE changing the ammo system, and should have a choice to "Please don't break my save" in a huge button, with a small button saying "I understand the consequences and wish to change the ammo system anyways". If the huge button is pressed, it SHOULD NOT change the ammo system. Otherwise, missclicks will ruin the savefile.

Right now, pressing the ammo systems button will switch over before the warning is issued, and the warning is issued on all screens. So, people press OK without thinking to Alt-F4 the game to recover the savefile if on an existing colony. Similarly, people will think they fucked up and it will all be fine when pressing the button _again_, except it isn't fine, which causes the bug as described (on-off-on).

**Comment by ErdeFB** [comment]
I can only speak for myself, but when I did this once I noticed the setting had toggled and fixed the situation appropriately. While it is always good to convey matters eloquently, please do not insult the intelligence of all users.
