### ISSUE TITLE
Released prisoners arm themselves

### ISSUE THREAD

**Issue by Caradog** [CombatExtendedRWMod/CombatExtended#836]
Prisoners seem to arm themselves on the way out after being released, going as far as to go back through doors to find nearby weapons.

**Comment by NoImageAvailable** [comment]
Same thing as #733

**Comment by NoImageAvailable** [comment]
Most likely due to the HCSK pick up weapons behavior firing when it shouldn't

**Comment by Totherphoenix** [comment]
This is not just occurring on release.

I had a prisoner repeatedly equipping himself with an Orbital Bombardment Device from my stockpile after I stripped him over and over again. It didn't look like he had any intention of using it, however if I released him, it would have meant I lost an Orbital Bombardment Device from my colony...

**Comment by Caradog** [comment]
Not sure if this is specific to the CE: FT edition but this is still occurring on 1.0
