### ISSUE TITLE
Starting new game with only CE - no UI, can't do anything

### ISSUE THREAD

**Issue by gustavpezka** [CombatExtendedRWMod/CombatExtended#892]
Started a new colony, map loaded with no tearrain and no objects. Also no UI elements, except helper and time control, and can't select anything. Turned on and off mods one by one, until I found the culprit - CE. Tried running only core and CE - still bugged. Edit: sorry, terrain and objects are present, just no UI and no selection/commands.

**Comment by LockdownX7** [comment]
If you're using the GitHub version of CE, make sure you're installing the latest version, [located here](https://github.com/NoImageAvailable/CombatExtended/releases/tag/v1.0.1.8). If you had an older version installed previously, make sure you delete it entirely before installing 1.8.0, to ensure no old files are kept.

If it's from the Steam workshop, you'll need to contact N7Huntsman, as that version is not published by us.

**Comment by AGenericName18** [comment]
I've been having this issue as well. (I tried both the Steam and the GitHub versions) I don't know if this helps at all, but I looked at the debug log when I started up a world, this error was spammed in the log: 
Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs () [0x00000] in <filename unknown>:0 
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x00000] in <filename unknown>:0 
  at Verse.Root.OnGUI () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.Root:OnGUI()

**Comment by gustavpezka** [comment]
Tried ver.1.8 from Git. Still nothing

**Comment by LockdownX7** [comment]
I don't know what to tell you, there's nothing in the recent CE versions that could be causing this error, and plenty of people are playing 1.8 with no issues. This seems like a specific issue with your local copy (have you done a manual install of CE where you put the files in the wrong place, perhaps?) so try doing a clean reinstall of RimWorld.

**Comment by NoImageAvailable** [comment]
Need an error log

**Comment by gustavpezka** [comment]
Will this do?
[2019-11-18_141320.zip](https://github.com/NoImageAvailable/CombatExtended/files/3858336/2019-11-18_141320.zip)

**Comment by gustavpezka** [comment]
Fresh install, only Hugslib and Github version 1.8 of CE in this one.

**Comment by gustavpezka** [comment]
Just the error.log
[error.log](https://github.com/NoImageAvailable/CombatExtended/files/3858693/error.log)

**Comment by GILoe** [comment]
Even if gustavpezka's log contain, the CE-FastTrack mod in it, having tested multiple versions of the mod (1.62 and 1.8 from you and the latest from CE-FT), the same NullReferenceExeption gets thrown onGUI() method [details in the output.txt file].
The game version for me is 1.0.2408, x32 if that helps you in any way.
Keep up the good work.

**Comment by Dyrewulfe** [comment]
Strangely enough, I've accidentally managed to reproduce this issue. Will report once I get a better feel for what's going here.
