### ISSUE TITLE
Zombieland & CE/CE:FT Conflict

### ISSUE THREAD

**Issue by Meronmero** [CombatExtendedRWMod/CombatExtended#945]
This doesn't generate any errors on the log.
Pawns and turrets will aim and shoot at walls when zombies are on the other side.
It will not do this for regular enemies such as Hostile Ancient Soldiers.

Tested using 3 mods.
[Mod Manager, CE, Zombieland]
[Mod Manager, CE:FT, Zombieland]

Both versions of CE cause this issue. Because turrets keep retargeting it causes a ton of lag when they're activated with zombies in their range.

**Comment by N7Huntsman** [comment]
There was a recent update to Zombieland, which included something in the changelog specifically addressing issues with Combat Extended and line-of-sight. Does this issue still persist?

**Comment by LockdownX7** [comment]
Can't reproduce with latest versions of CE + ZL.
