### ISSUE TITLE
[Fix in comments] Prometheum and FSX auto delete

### ISSUE THREAD

**Issue by Hairetik0s** [CombatExtendedRWMod/CombatExtended#970]
With dev mode, I can place prometheum and fsx, but once I unpause, they automatically get deleted. The plants and animals that give them also seem to be growing/producing fine. Seems like the items just disappear right after being created. The ammo system has been off the whole game.

**Comment by N7Huntsman** [comment]
Please provide a log and a full modlist. Then, test with **only** Core and Combat Extended loaded and try to replicate the issue.

**Comment by ZedDarius** [comment]
The problem has been observed and replicated elsewhere.

Mods in use: Combat Extended.

Issue: When "Enable ammunition system" in the mod options is disabled, any produced or placed FSX and Prometheum immediately despawn and disappear from the world.

* FSX and Prometheum are available for purchase from traders or faction bases, but after purchasing them they vanish from the world and/or caravan inventory.

* Pausing, entering development mode, and manually placing FSX and Prometheum causes them to appear, but once the game is unpaused they vanish.  The debug log within development mode reveals no information when this process is repeated.

* FSX and Prometheum production methods suffer from the same issues.  e.g. FSX produced from Boomalope milking disappears instantly; when the mod "Chemical Distilling for Combat Extended" is enabled, the crafting job is created at the biofuel refinery and pawns craft, but when completed the product vanishes.

* Other methods of putting FSX and Prometheum into the world suffer from the same issues.  e,g, the mod "EdB Prepare Carefully" is enabled and used to give the starting base FSX and Prometheum, but when the pods land, the FSX and Prometheum immediately disappear.

**Comment by N7Huntsman** [comment]
As I don't play with ammo disabled, can I ask what FSX and Prometheum are needed for in this case?

**Comment by ZedDarius** [comment]
Off the top of my head, the vanilla IED recipes have been changed from requiring 81mm mortar shells to two units of FSX for the normal one and two units of Prometheum.  The 81mm mortar shells themselves also require FSX or Prometheum, so anything dependent on them for construction in other mods cannot be built.  Which, technically, is the responsibility of other modders, but bears mentioning.

**Comment by Hairetik0s** [comment]
Yep, the normal and incendiary IEDs, and also molotovs and sticky bombs need Prometheum and FSX, respectively, to craft. Frag grenades might need FSX too, but I'd have to check.

**Comment by Alicecomma** [comment]
I'm certain this is because of the previous changes making them ammodefs, allowing Prometheum and FSX to cook off upon taking damage.

Either cooking off functionality should be handled by a comp or a parent def of both ammo and cooking off resources, the two resources should not cook off, or the two resources should not be disabled along with the ammo system.

**Comment by Alicecomma** [comment]
So, the problem is in AmmoThing. The following lines should be changed:

```
if (!Controller.settings.EnableAmmoSystem && !def.IsWeapon) Destroy(DestroyMode.Vanish);
```

to

```
if (!Controller.settings.EnableAmmoSystem && !def.IsWeapon && def is AmmoDef) Destroy(DestroyMode.Vanish);
```

----

This way, AmmoThings (Things which cook off when taking damage) are only immediately destroyed with ammo system disabled if their def is AmmoDef. This should exclude FSX/Prometheum from being destroyed
