### ISSUE TITLE
Alt.: GrenadeRecipeBase sets recipeUsers; some ammo uses GrenadeRecipeBase

### ISSUE THREAD

**Issue by rimpy-custom** [CombatExtendedRWMod/CombatExtended#975]
Looks like there are four types of ammo that are not used anywhere in Combat Extended but you are able to craft them on machining table:
100x691mm HE
100x691mm HEAT
120mm HE
120mm HEAT
Probably, should be deleted from Defs or moved to appropriate patch.

**Comment by rimpy-custom** [comment]
Not an issue of CE, but CE:FT.

**Comment by Alicecomma** [comment]
The 1.1 "60mm mortar shells" have the same problem, they should not use GrenadeRecipeBase. They should use AmmoRecipeBase.

**Comment by N7Huntsman** [comment]
@Alicecomma I've corrected the ammo recipe base for the 100mmR and 120mm in #1136 

However, 60mm does not currently use 'GrenadeRecipeBase' and since I used the 81mm .xml file as a template, I suspect it never has.

**Comment by Alicecomma** [comment]
The 60mm shell is probably due to the weapon being considered a turret gun, so the destroyOnDrop is not checked -- OR, the weapon isn't destroyOnDrop.

**Comment by N7Huntsman** [comment]
All cases in core ammo and integrated patches has been solved. The issue with the 60mm was unrelated.
