### ISSUE TITLE
Reloading Job takes a lot of CPU time

### ISSUE THREAD

**Issue by rimpy-custom** [CombatExtendedRWMod/CombatExtended#980]
According to Dubs Performance Analyzer, Reloading Job takes 0.8ms but any other job takes 0.08-0.15ms. Also CE improves garbage collector spikes (more frequent and strong). Are there planned any performance optimization in future? I like CE and will play it, but you know, better performance is always good.

**Comment by zozilin** [comment]
Not in the nearest future, no. We don't have a dedicated C# coder at the moment and I suspect this is up their valley.

**Comment by Alicecomma** [comment]
I could imagine the reloading job taking ages. The code seems highly redundant in places, often creating and iterating collections. Looking through all code and rewriting where possible seems in order.

**Comment by Alicecomma** [comment]
If this issue is related to the turret reload workgiver, this makes sense. The workgiver looks through an 80 tile radius for ammo.

**Comment by Alicecomma** [comment]
Fixed in most recent turret rewrite. Previously, jobs would be checked very, very often.
